---
title: "week 4 homework"
output: html_document
date: '2022-10-26'
---

Packages used for task

```{r message = FALSE, warning=FALSE}
library(tidyverse)
library(sf)
```

1. Read in global gender inequality data 

```{r message=FALSE, warning=FALSE}
# read in gender inequality data
gii<- read_csv("HDR21-22_Composite_indices_complete_time_series.csv")

# subset to essential info and gender inequality index in 2010 and 2019
gii_sub <- gii %>%
  select(iso3, country, gii_2010, gii_2019)
```

2. Join the global gender inequality index to spatial data of the World, creating a new column of difference in inequality

```{r}
# load in spatial data of the world
world <- st_read("World_Countries_(Generalized)/World_Countries__Generalized_.shp")

# join the gii to the world spatial data
gii_world <- world %>%
  left_join(., gii_sub, by = c('ISO' = 'iso3'))

# make column for difference in gii in 2010 and 2019
gii_sub <- gii_sub %>%
  mutate(gii_dif = gii_2019 - gii_2010)
```

Here have joined on ISO 3 and ISO 2, needs to be the same....

```{r}

library(countrycode)
gii_sub2 <- gii_sub %>%
  #not needed here as we can now use the country name...but see below
  mutate(iso_code2=countrycode(country, origin = 'country.name', destination = 'iso2c'))

gii_world2 <- world %>%
  left_join(., gii_sub2, by = c('ISO' = 'iso_code2'))
```


3. Mapping

```{r}
library(tmap)
tmap_mode("plot")
qtm(gii_world2,
    fill="gii_dif")
```

```{r}
breaks=c(0.0,0.2,0.4,0.6,0.8,1.0)
diffbreaks=c(-0.4,-0.3,-0.2,-0.1,0,0.1)
# preserve size not direction like WGS84
joinshp = st_transform(gii_world2, crs = "+proj=moll")

# plot each map
tm1 <- tm_shape(joinshp) + 
  tm_polygons("gii_2019", 
              breaks=breaks,
              palette="PuBu")+
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(a)", position=c(0,0.85), size=1.5)


tm2 <- tm_shape(joinshp) + 
  tm_polygons("gii_2010",
              breaks=breaks,
              palette="PuBu") + 
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(b)", position=c(0,0.85), size=1.5)

tm3 <- tm_shape(joinshp) + 
  tm_polygons("gii_dif",
              #style="fixed",
              breaks=diffbreaks,
              palette=("Blues"),
               midpoint = NA) + 
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(c)", position=c(0,0.85), size=1.5)

legend <- tm_shape(joinshp) + 
  tm_polygons("gii_2019", 
              breaks=breaks,
              palette="PuBu",
              title = "GII")+
  tm_legend(show=TRUE)+
  #asp is aspect ratio! 
  tm_layout(legend.only = TRUE, legend.position=c(0.3,0.25),asp=0.1)+
  tm_shape(joinshp) +
  tm_polygons("gii_dif",
                 palette=("Blues"),
               midpoint = NA,
               title="GII difference \n(2019-2010)") +
    #tm_scale_bar(position=c(0.2,0.04), text.size=0.6)+
    tm_compass(north=0, position=c(0.6,0.6))+
    tm_layout(legend.only = TRUE, legend.position=c(0.1,0.1),asp=0.1)+
    tm_credits("Mapped data:\nUN Gender Inequality Index\nWorld outline:\nArcGIS Hub 
               ", position=c(0.35,0.2), just="left")
# in tmap can't make legends side by side unless use this workaround: 
#https://github.com/r-tmap/tmap/issues/476 
t=tmap_arrange(tm1, tm2, tm3, legend, ncol=2)
t
```

```

